### ISSUE TITLE
2023-OCT

### ISSUE THREAD

**Issue by OldManDoug** [YKLoh666/AACS2204-Past-Year-Answer#1]

**Comment by YKLoh666** [comment]
Done assigned :D

**Comment by OldManDoug** [comment]
> #Question 1L 
a. 1. Encapsulation; the process of hiding the impleementation and variables

**Comment by YKLoh666** [comment]
Hihi are you still cooking the answer?

**Comment by OldManDoug** [comment]
yes yes still cooking -- sowee its taking a bit long(busy)
